"""Shared UI sizing tokens for buttons and dialogs."""

ACTION_BUTTON_HEIGHT = 28
NAV_BUTTON_HEIGHT = 36
DIALOG_BUTTON_HEIGHT = 32
DIALOG_BUTTON_MIN_WIDTH = 88
DIALOG_FIELD_HEIGHT = 44
DIALOG_MARGINS = (16, 14, 16, 24)
DIALOG_SPACING = 10
DIALOG_DEFAULT_WIDTH = 380
DIALOG_FORM_WIDTH = 620
PROJECT_DIALOG_WIDTH = 720
PROJECT_DIALOG_HEIGHT = 700
FINDING_DIALOG_HEIGHT = 440
PROJECT_TOOLBAR_BUTTON_HEIGHT = 28
ROUND_REFRESH_BUTTON_SIZE = 28
