from __future__ import annotations

import html
from datetime import datetime
from pathlib import Path

from core.db import Project
from core.exporters.case_context import build_case_context, context_cards_html
from core.exporters.template_utils import load_template, logo_data_uri, render_template
from core.output_language import normalize_output_language


def export_table_html(
    file_path: str,
    title: str,
    headers: list[str],
    rows: list[list[str]],
    *,
    lang: str = "en",
    project: Project | None = None,
    project_name: str = "",
    source_label: str = "",
) -> None:
    language = normalize_output_language(lang, default="en")
    text = _report_text(language)
    case_context = build_case_context(project, project_name=project_name)

    table_headers = "".join(f"<th>{html.escape(str(header))}</th>" for header in headers)
    table_rows = "\n".join(
        "<tr>"
        + "".join(f"<td>{html.escape(str(value))}</td>" for value in row)
        + "</tr>"
        for row in rows
    )

    rendered = render_template(
        load_template("table_export.html"),
        {
            "LANG": language,
            "TITLE": text["title"],
            "REPORT_TITLE": title or text["table_title"],
            "LOGO": logo_data_uri(),
            "EXPORTED_LABEL": text["exported"],
            "EXPORTED_AT": datetime.now().strftime("%d.%m.%Y %H:%M:%S"),
            "SOURCE_LABEL": text["source"],
            "SOURCE": source_label or "—",
            "ROWS_LABEL": text["rows"],
            "ROWS_COUNT": len(rows),
            "COLUMNS_LABEL": text["columns"],
            "COLUMNS_COUNT": len(headers),
            "CASE_CONTEXT_CARDS": context_cards_html(case_context, card_class="info"),
            "TABLE_TITLE": text["table_title"],
            "TABLE_HEADERS": table_headers,
            "TABLE_ROWS": table_rows,
            "GENERATED_BY_LABEL": text["generated_by"],
        },
        escape_values=False,
    )
    Path(file_path).write_text(rendered, encoding="utf-8")


def _report_text(language: str) -> dict[str, str]:
    if normalize_output_language(language, default="en") == "hr":
        return {
            "title": "ViaNyquist tablicni izvoz",
            "exported": "Izvezeno",
            "source": "Izvor",
            "rows": "Redovi",
            "columns": "Stupci",
            "table_title": "Podaci tablice",
            "generated_by": "Generirano pomocu",
        }
    return {
        "title": "ViaNyquist Table Export",
        "exported": "Exported",
        "source": "Source",
        "rows": "Rows",
        "columns": "Columns",
        "table_title": "Table data",
        "generated_by": "Generated by",
    }
